FROM node:alpine

LABEL authors="Andrey Ponomarev"

WORKDIR /node

COPY package*.json ./

RUN npm install

# 'npm ci' is alternative to 'npm install - https://stackoverflow.com/a/53325242/13156302
# '--only=production' allow us to install only 'dependencies', skipping 'devDependencies' from package.json

RUN npm ci --only=production

CMD npm run serve:prod
