FROM node:alpine
LABEL authors="Andrey Ponomarev"
WORKDIR /node

COPY package*.json ./
RUN npm install

USER node

# This will copy everything from the source path 
# (it is more of a convenience when testing locally)
COPY . .

# 'npm ci' - https://stackoverflow.com/a/53325242/13156302
# '--only=production' allow us to install only 'dependencies', skipping 'devDependencies' from package.json
RUN npm ci --only=production

# Bundle app source
COPY . /app
CMD npm run serve:prod
